### ISSUE TITLE
Deploying it on my work channel

### ISSUE THREAD

**Issue by ohassidi** [kosyfrances/gitlab_mr_bot#2]
Hey is this working? I am a newbie with all slack bot stuff. Can you please guide me step by step how to deploy it on my work space
Thanks

**Comment by kosyfrances** [comment]
Hi @ohassidi Apologies for the late response. As at when it was built, it was working. Was the readme helpful? I'll find time to update it with more info on how to set it up.

**Comment by kosyfrances** [comment]
Hi @ohassidi do you still need help?

**Comment by ohassidi** [comment]
No thanks
